# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(573, 659)
        MainWindow.setAcceptDrops(False)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(30, 40, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.inputType = QtWidgets.QComboBox(self.centralWidget)
        self.inputType.setGeometry(QtCore.QRect(130, 40, 104, 26))
        self.inputType.setObjectName("inputType")
        self.inputType.addItem("")
        self.inputType.addItem("")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(30, 70, 541, 16))
        self.label_3.setObjectName("label_3")
        self.inputText = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.inputText.setGeometry(QtCore.QRect(30, 90, 511, 111))
        self.inputText.setObjectName("inputText")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(30, 210, 401, 16))
        self.label_4.setObjectName("label_4")
        self.inputFile = QtWidgets.QPushButton(self.centralWidget)
        self.inputFile.setGeometry(QtCore.QRect(20, 230, 101, 32))
        self.inputFile.setObjectName("inputFile")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(120, 240, 93, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(30, 270, 341, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.inputMers = QtWidgets.QListWidget(self.centralWidget)
        self.inputMers.setGeometry(QtCore.QRect(30, 290, 111, 71))
        self.inputMers.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.inputMers.setObjectName("inputMers")
        item = QtWidgets.QListWidgetItem()
        self.inputMers.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.inputMers.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.inputMers.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.inputMers.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.inputMers.addItem(item)
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(30, 380, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.inputHLACategory = QtWidgets.QComboBox(self.centralWidget)
        self.inputHLACategory.setGeometry(QtCore.QRect(30, 400, 91, 26))
        self.inputHLACategory.setObjectName("inputHLACategory")
        self.inputHLACategory.addItem("")
        self.inputHLACategory.addItem("")
        self.inputHLACategory.addItem("")
        self.inputHLACategory.addItem("")
        self.inputHLACategory.addItem("")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(30, 430, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.inputHLAallele = QtWidgets.QListWidget(self.centralWidget)
        self.inputHLAallele.setGeometry(QtCore.QRect(30, 450, 111, 121))
        self.inputHLAallele.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.inputHLAallele.setObjectName("inputHLAallele")
        self.label_9 = QtWidgets.QLabel(self.centralWidget)
        self.label_9.setGeometry(QtCore.QRect(30, 580, 231, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralWidget)
        self.label_10.setGeometry(QtCore.QRect(30, 610, 231, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.thresholdStrong = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.thresholdStrong.setEnabled(True)
        self.thresholdStrong.setGeometry(QtCore.QRect(270, 570, 68, 24))
        self.thresholdStrong.setSingleStep(0.01)
        self.thresholdStrong.setProperty("value", 0.5)
        self.thresholdStrong.setObjectName("thresholdStrong")
        self.thresholdWeak = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.thresholdWeak.setGeometry(QtCore.QRect(270, 600, 68, 24))
        self.thresholdWeak.setSingleStep(0.01)
        self.thresholdWeak.setProperty("value", 2.0)
        self.thresholdWeak.setObjectName("thresholdWeak")
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "pyBind"))
        self.label.setText(_translate("MainWindow", "Submission"))
        self.label_2.setText(_translate("MainWindow", "Type of input"))
        self.inputType.setItemText(0, _translate("MainWindow", "Fasta"))
        self.inputType.setItemText(1, _translate("MainWindow", "Peptide"))
        self.label_3.setText(_translate("MainWindow", "Paste a single sequence or several sequencies in FASTA format into the field below:"))
        self.label_4.setText(_translate("MainWindow", "or submit a file a file in Fasta format directly from your local disk:"))
        self.inputFile.setText(_translate("MainWindow", "Choose file"))
        self.label_5.setText(_translate("MainWindow", "no file selected"))
        self.label_6.setText(_translate("MainWindow", "Peptide length (you may select multiple lengths)"))
        __sortingEnabled = self.inputMers.isSortingEnabled()
        self.inputMers.setSortingEnabled(False)
        item = self.inputMers.item(0)
        item.setText(_translate("MainWindow", "8mer peptides"))
        item = self.inputMers.item(1)
        item.setText(_translate("MainWindow", "9mer peptides"))
        item = self.inputMers.item(2)
        item.setText(_translate("MainWindow", "10mer peptides"))
        item = self.inputMers.item(3)
        item.setText(_translate("MainWindow", "11mer peptides"))
        item = self.inputMers.item(4)
        item.setText(_translate("MainWindow", "12mer peptides"))
        self.inputMers.setSortingEnabled(__sortingEnabled)
        self.label_7.setText(_translate("MainWindow", "Select loci"))
        self.inputHLACategory.setItemText(0, _translate("MainWindow", "All HLAs"))
        self.inputHLACategory.setItemText(1, _translate("MainWindow", "HLA-A"))
        self.inputHLACategory.setItemText(2, _translate("MainWindow", "HLA-B"))
        self.inputHLACategory.setItemText(3, _translate("MainWindow", "HLA-C"))
        self.inputHLACategory.setItemText(4, _translate("MainWindow", "HLA-E"))
        self.label_8.setText(_translate("MainWindow", "Select allele"))
        self.label_9.setText(_translate("MainWindow", "Threshold for strong binder: % Rank"))
        self.label_10.setText(_translate("MainWindow", "Threshold for weak binder: % Rank"))

